spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/lojadigitaldb
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

server:
  port: 8080